name: MonsterBox
main: tux2.MonsterBox.MonsterBox
version: 1.3
commands:
   mbox:
      description: Sets the monster spawner you are looking at to the specified mob type.
      usage: |
       /mbox set <mob name>
softdepend: [Spout,Vault,TuxTwoLib]

# SuperPerms data
permissions:
    monsterbox.*:
        default: op
        description: Gives access to all commands and abilities
        children:
            monsterbox.eggset: true
            monsterbox.set: true
            monsterbox.drops: true
            monsterbox.dropegg.*: true
            monsterbox.free: true
            monsterbox.freeegg: true
            monsterbox.place: true
            monsterbox.view: true
            monsterbox.spawn.*: true
            monsterbox.eggspawn.*: true
            monsterbox.eggthrow.*: true
    monsterbox.spawn.*:
        default: op
        description: Gives access to change a mob spawner to any type
        children:
            monsterbox.spawn.pig: true
            monsterbox.spawn.chicken: true
            monsterbox.spawn.cow: true
            monsterbox.spawn.sheep: true
            monsterbox.spawn.squid: true
            monsterbox.spawn.creeper: true
            monsterbox.spawn.ghast: true
            monsterbox.spawn.pigzombie: true
            monsterbox.spawn.skeleton: true
            monsterbox.spawn.spider: true
            monsterbox.spawn.zombie: true
            monsterbox.spawn.slime: true
            monsterbox.spawn.monster: true
            monsterbox.spawn.giant: true
            monsterbox.spawn.wolf: true
            monsterbox.spawn.cavespider: true
            monsterbox.spawn.enderman: true
            monsterbox.spawn.silverfish: true
            monsterbox.spawn.enderdragon: true
            monsterbox.spawn.villager: true
            monsterbox.spawn.blaze: true
            monsterbox.spawn.mushroomcow: true
            monsterbox.spawn.magmacube: true
            monsterbox.spawn.snowman: true
            monsterbox.spawn.irongolem: true
            monsterbox.spawn.ocelot: true
            monsterbox.spawn.horse: true
            monsterbox.spawn.endermite: true
            monsterbox.spawn.guardian: true
            monsterbox.spawn.rabbit: true
            monsterbox.spawn.shulker: true
    monsterbox.dropegg.*:
        default: op
        description: Gives access to change a mob spawner to any type
        children:
            monsterbox.dropegg.pig: true
            monsterbox.dropegg.chicken: true
            monsterbox.dropegg.cow: true
            monsterbox.dropegg.sheep: true
            monsterbox.dropegg.squid: true
            monsterbox.dropegg.creeper: true
            monsterbox.dropegg.ghast: true
            monsterbox.dropegg.pigzombie: true
            monsterbox.dropegg.skeleton: true
            monsterbox.dropegg.spider: true
            monsterbox.dropegg.zombie: true
            monsterbox.dropegg.slime: true
            monsterbox.dropegg.monster: true
            monsterbox.dropegg.giant: true
            monsterbox.dropegg.wolf: true
            monsterbox.dropegg.cavespider: true
            monsterbox.dropegg.enderman: true
            monsterbox.dropegg.silverfish: true
            monsterbox.dropegg.enderdragon: true
            monsterbox.dropegg.villager: true
            monsterbox.dropegg.blaze: true
            monsterbox.dropegg.mushroomcow: true
            monsterbox.dropegg.magmacube: true
            monsterbox.dropegg.snowman: true
            monsterbox.dropegg.irongolem: true
            monsterbox.dropegg.ocelot: true
            monsterbox.dropegg.horse: true
            monsterbox.dropegg.endermite: true
            monsterbox.dropegg.guardian: true
            monsterbox.dropegg.rabbit: true
            monsterbox.dropegg.shulker: true
    monsterbox.eggspawn.*:
        default: op
        description: Gives access to change a mob spawner to any type using eggs
        children:
            monsterbox.eggspawn.pig: true
            monsterbox.eggspawn.chicken: true
            monsterbox.eggspawn.cow: true
            monsterbox.eggspawn.sheep: true
            monsterbox.eggspawn.squid: true
            monsterbox.eggspawn.creeper: true
            monsterbox.eggspawn.ghast: true
            monsterbox.eggspawn.pigzombie: true
            monsterbox.eggspawn.skeleton: true
            monsterbox.eggspawn.spider: true
            monsterbox.eggspawn.zombie: true
            monsterbox.eggspawn.slime: true
            monsterbox.eggspawn.monster: true
            monsterbox.eggspawn.giant: true
            monsterbox.eggspawn.wolf: true
            monsterbox.eggspawn.cavespider: true
            monsterbox.eggspawn.enderman: true
            monsterbox.eggspawn.silverfish: true
            monsterbox.eggspawn.enderdragon: true
            monsterbox.eggspawn.villager: true
            monsterbox.eggspawn.blaze: true
            monsterbox.eggspawn.mushroomcow: true
            monsterbox.eggspawn.magmacube: true
            monsterbox.eggspawn.snowman: true
            monsterbox.eggspawn.irongolem: true
            monsterbox.eggspawn.ocelot: true
            monsterbox.eggspawn.horse: true
            monsterbox.eggspawn.endermite: true
            monsterbox.eggspawn.guardian: true
            monsterbox.eggspawn.rabbit: true
            monsterbox.eggspawn.shulker: true
    monsterbox.eggthrow.*:
        default: op
        description: Gives access to change a mob spawner to any type using eggs
        children:
            monsterbox.eggthrow.pig: true
            monsterbox.eggthrow.chicken: true
            monsterbox.eggthrow.cow: true
            monsterbox.eggthrow.sheep: true
            monsterbox.eggthrow.squid: true
            monsterbox.eggthrow.creeper: true
            monsterbox.eggthrow.ghast: true
            monsterbox.eggthrow.pigzombie: true
            monsterbox.eggthrow.skeleton: true
            monsterbox.eggthrow.spider: true
            monsterbox.eggthrow.zombie: true
            monsterbox.eggthrow.slime: true
            monsterbox.eggthrow.monster: true
            monsterbox.eggthrow.giant: true
            monsterbox.eggthrow.wolf: true
            monsterbox.eggthrow.cavespider: true
            monsterbox.eggthrow.enderman: true
            monsterbox.eggthrow.silverfish: true
            monsterbox.eggthrow.enderdragon: true
            monsterbox.eggthrow.villager: true
            monsterbox.eggthrow.blaze: true
            monsterbox.eggthrow.mushroomcow: true
            monsterbox.eggthrow.magmacube: true
            monsterbox.eggthrow.snowman: true
            monsterbox.eggthrow.irongolem: true
            monsterbox.eggthrow.ocelot: true
            monsterbox.eggthrow.horse: true
            monsterbox.eggthrow.endermite: true
            monsterbox.eggthrow.guardian: true
            monsterbox.eggthrow.rabbit: true
            monsterbox.eggthrow.shulker: true
    monsterbox.set:
        description: Allows you to set a monster spawner type.
        default: op
        command: "/mbox set [monster]"
    monsterbox.eggset:
        description: Allows you to set a monster spawner type using eggs.
        default: op
    monsterbox.view:
        description: Allows you to get the type of the monster spawner.
        default: op
        command: "/mbox get"
    monsterbox.drops:
        description: Allows the ability for the player to recieve a drop from breaking spawners.
        default: op
    monsterbox.dropegg:
        description: Allows the ability for the player to recieve an egg drop from breaking spawners.
        default: op
    monsterbox.free:
        description: if an economy is enabled this node lets this group/user use the /mbox set command for free
        default: op
    monsterbox.freeegg:
        description: if an economy is enabled this node lets this group/user set spawners using eggs for free
        default: op
    monsterbox.place:
        description: Allows you to place any spawner block
        default: op
    monsterbox.spawn.pig:
        description: Allows you to set any spawner to be a pig spawner.
        default: op
        command: "/mbox set pig"
    monsterbox.spawn.chicken:
        description: Allows you to set any spawner to be a chicken spawner.
        default: op
        command: "/mbox set chicken"
    monsterbox.spawn.cow:
        description: Allows you to set any spawner to be a cow spawner.
        default: op
        command: "/mbox set cow"
    monsterbox.spawn.sheep:
        description: Allows you to set any spawner to be a sheep spawner.
        default: op
        command: "/mbox set sheep"
    monsterbox.spawn.squid:
        description: Allows you to set any spawner to be a squid spawner.
        default: op
        command: "/mbox set squid"
    monsterbox.spawn.creeper:
        description: Allows you to set any spawner to be a creeper spawner.
        default: op
        command: "/mbox set creeper"
    monsterbox.spawn.ghast:
        description: Allows you to set any spawner to be a ghast spawner.
        default: op
        command: "/mbox set ghast"
    monsterbox.spawn.pigzombie:
        description: Allows you to set any spawner to be a pig zombie spawner.
        default: op
        command: "/mbox set pigzombie"
    monsterbox.spawn.skeleton:
        description: Allows you to set any spawner to be a skeleton spawner.
        default: op
        command: "/mbox set skeleton"
    monsterbox.spawn.spider:
        description: Allows you to set any spawner to be a spider spawner.
        default: op
        command: "/mbox set spider"
    monsterbox.spawn.zombie:
        description: Allows you to set any spawner to be a zombie spawner.
        default: op
        command: "/mbox set zombie"
    monsterbox.spawn.slime:
        description: Allows you to set any spawner to be a slime spawner.
        default: op
        command: "/mbox set slime"
    monsterbox.spawn.monster:
        description: Allows you to set any spawner to be a monster (aka steve) spawner.
        default: op
        command: "/mbox set monster"
    monsterbox.spawn.giant:
        description: Allows you to set any spawner to be a giant spawner.
        default: op
        command: "/mbox set giant"
    monsterbox.spawn.wolf:
        description: Allows you to set any spawner to be a wolf spawner.
        default: op
        command: "/mbox set wolf"
    monsterbox.spawn.cavespider:
        description: Allows you to set any spawner to be a cave spider spawner.
        default: op
        command: "/mbox set cavespider"
    monsterbox.spawn.enderman:
        description: Allows you to set any spawner to be an enderman spawner.
        default: op
        command: "/mbox set enderman"
    monsterbox.spawn.silverfish:
        description: Allows you to set any spawner to be a silverfish spawner.
        default: op
        command: "/mbox set silverfish"
    monsterbox.spawn.enderdragon:
        description: Allows you to set any spawner to be an ender dragon spawner.
        default: op
        command: "/mbox set EnderDragon"
    monsterbox.spawn.villager:
        description: Allows you to set any spawner to be a villager spawner.
        default: op
        command: "/mbox set villager"
    monsterbox.spawn.blaze:
        description: Allows you to set any spawner to be a blaze spawner.
        default: op
        command: "/mbox set blaze"
    monsterbox.spawn.mushroomcow:
        description: Allows you to set any spawner to be a mushroom cow spawner.
        default: op
        command: "/mbox set mushroomcow"
    monsterbox.spawn.magmacube:
        description: Allows you to set any spawner to be a magma cube spawner.
        default: op
        command: "/mbox set magmacube"
    monsterbox.spawn.snowman:
        description: Allows you to set any spawner to be a snowman spawner.
        default: op
        command: "/mbox set snowman"
    monsterbox.spawn.horse:
        description: Allows you to set any spawner to be a horse spawner.
        default: op
        command: "/mbox set horse"
    monsterbox.spawn.endermite:
        description: Allows you to set any spawner to be a endermite spawner.
        default: op
        command: "/mbox set endermite"
    monsterbox.spawn.guardian:
        description: Allows you to set any spawner to be a guardian spawner.
        default: op
        command: "/mbox set guardian"
    monsterbox.spawn.rabbit:
        description: Allows you to set any spawner to be a rabbit spawner.
        default: op
        command: "/mbox set rabbit"
    monsterbox.spawn.shulker:
        description: Allows you to set any spawner to be a shulker spawner.
        default: op
        command: "/mbox set shulker"
    monsterbox.eggspawn.pig:
        description: Allows you to set any spawner to be a pig spawner using eggs.
        default: op
    monsterbox.eggspawn.chicken:
        description: Allows you to set any spawner to be a chicken spawner using eggs.
        default: op
    monsterbox.eggspawn.cow:
        description: Allows you to set any spawner to be a cow spawner using eggs.
        default: op
    monsterbox.eggspawn.sheep:
        description: Allows you to set any spawner to be a sheep spawner using eggs.
        default: op
    monsterbox.eggspawn.squid:
        description: Allows you to set any spawner to be a squid spawner using eggs.
        default: op
    monsterbox.eggspawn.creeper:
        description: Allows you to set any spawner to be a creeper spawner using eggs.
        default: op
    monsterbox.eggspawn.ghast:
        description: Allows you to set any spawner to be a ghast spawner using eggs.
        default: op
    monsterbox.eggspawn.pigzombie:
        description: Allows you to set any spawner to be a pig zombie spawner using eggs.
        default: op
    monsterbox.eggspawn.skeleton:
        description: Allows you to set any spawner to be a skeleton spawner using eggs.
        default: op
    monsterbox.eggspawn.spider:
        description: Allows you to set any spawner to be a spider spawner using eggs.
        default: op
    monsterbox.eggspawn.zombie:
        description: Allows you to set any spawner to be a zombie spawner using eggs.
        default: op
    monsterbox.eggspawn.slime:
        description: Allows you to set any spawner to be a slime spawner using eggs.
        default: op
    monsterbox.eggspawn.monster:
        description: Allows you to set any spawner to be a monster (aka steve) spawner using eggs.
        default: op
    monsterbox.eggspawn.giant:
        description: Allows you to set any spawner to be a giant spawner using eggs.
        default: op
    monsterbox.eggspawn.wolf:
        description: Allows you to set any spawner to be a wolf spawner using eggs.
        default: op
    monsterbox.eggspawn.cavespider:
        description: Allows you to set any spawner to be a cave spider spawner using eggs.
        default: op
    monsterbox.eggspawn.enderman:
        description: Allows you to set any spawner to be an enderman spawner using eggs.
        default: op
    monsterbox.eggspawn.silverfish:
        description: Allows you to set any spawner to be a silverfish spawner using eggs.
        default: op
    monsterbox.eggspawn.enderdragon:
        description: Allows you to set any spawner to be an ender dragon spawner using eggs.
        default: op
    monsterbox.eggspawn.villager:
        description: Allows you to set any spawner to be a villager spawner using eggs.
        default: op
    monsterbox.eggspawn.blaze:
        description: Allows you to set any spawner to be a blaze spawner using eggs.
        default: op
    monsterbox.eggspawn.mushroomcow:
        description: Allows you to set any spawner to be a mushroom cow spawner using eggs.
        default: op
    monsterbox.eggspawn.magmacube:
        description: Allows you to set any spawner to be a magma cube spawner using eggs.
        default: op
    monsterbox.eggspawn.snowman:
        description: Allows you to set any spawner to be a snowman spawner using eggs.
        default: op
    monsterbox.eggspawn.horse:
        description: Allows you to set any spawner to be a horse spawner using eggs.
        default: op
    monsterbox.eggspawn.guardian:
        description: Allows you to set any spawner to be a guardian spawner using eggs.
        default: op
    monsterbox.eggspawn.endermite:
        description: Allows you to set any spawner to be an endermite spawner using eggs.
        default: op
    monsterbox.eggspawn.rabbit:
        description: Allows you to set any spawner to be a rabbit spawner using eggs.
        default: op
    monsterbox.eggspawn.shulker:
        description: Allows you to set any spawner to be a shulker spawner using eggs.
        default: op